## Key Components
1. Modules (Layers)
2. ActivationFunctions
3. Loss Functions
4. Container Modules
5. Regularization and Dropout

In [2]:
import torch
import torch.nn as nn

In [3]:
# Create a Model class
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    #Forward Pass
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [4]:
# Simple dataset
features = torch.rand(10,5)

# Create model
model = Model(features.shape[1])

#Forward pass
model(features)

tensor([[0.6061],
        [0.6500],
        [0.6482],
        [0.6669],
        [0.6588],
        [0.6415],
        [0.6432],
        [0.6839],
        [0.6832],
        [0.6397]], grad_fn=<SigmoidBackward0>)

In [5]:
#show weights
model.linear.weight

Parameter containing:
tensor([[-0.1463, -0.0830,  0.3131,  0.2628,  0.1875]], requires_grad=True)

In [6]:
#Show bias 
model.linear.bias

Parameter containing:
tensor([0.4463], requires_grad=True)

In [7]:
! pip install torchinfo

In [8]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00