In [58]:
import torch
print(torch.__version__)

2.10.0+cu128


In [59]:
if torch.cuda.is_available():
    print(f"Device: {torch.cuda.get_device_name(0)}")
else: 
    print("Device not available.")

Device: NVIDIA GeForce RTX 4060 Laptop GPU


In [60]:
# empty

a = torch.empty(2,3)
a

tensor([[-2.8538e+21,  3.0880e-41,  0.0000e+00],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

In [61]:
#check type
type(a)

torch.Tensor

In [62]:
#shape
print(a.shape)
#size
print(a.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [63]:
# using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [64]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [65]:
# random tensors
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [66]:
#Use of seeds
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [67]:
#Custom tensor
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [68]:
# other ways to create a tensor

#arange
print("Using arange--> ", torch.arange(0,10,2))

#using linspace
print("Using linspace--> ", torch.linspace(0,10,10))

# Using eye
print("Using Eye(Identity matrix)--> ", torch.eye(5))

# Using Full
print("Using Full--> ", torch.full((3,3), 5))

Using arange-->  tensor([0, 2, 4, 6, 8])
Using linspace-->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using Eye(Identity matrix)-->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using Full-->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [69]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [70]:
# Same shape different values
torch.empty_like(x)

tensor([[94652036388912,              0,              3],
        [             4,              5,              6]])

In [71]:
# Similarli zeroes _like and ones_like
print(torch.zeros_like(x))
print(torch.ones_like(x))

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])


## Tensor Data Types

In [72]:
x.dtype

torch.int64

In [73]:
torch.tensor([1.0,2.0,3.0], dtype=torch.float32)

tensor([1., 2., 3.])

In [74]:
# Changing data type
x.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## Maths Operations

In [75]:
#Scalar operations

#Add
x + 2

#Subtract
x -2

#Multiply
x*3

#Divide
x/2

#Power
x**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

## Element wise Operations

In [76]:
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[n for n in range(4,7)],[n for n in range(1,4)]])

#ADD
print(x+y)

#SUB
print(x-y)

#MUL
print(x*y)

#DIV
print(x/y)

#POWER
print(x**y)

#abs
print(abs(x-y))

#negative
print(torch.neg(abs(x-y)))

#round, floor, ceil

#clamp
torch.clamp(x,min=1,max=3)


tensor([[5, 7, 9],
        [5, 7, 9]])
tensor([[-3, -3, -3],
        [ 3,  3,  3]])
tensor([[ 4, 10, 18],
        [ 4, 10, 18]])
tensor([[0.2500, 0.4000, 0.5000],
        [4.0000, 2.5000, 2.0000]])
tensor([[  1,  32, 729],
        [  4,  25, 216]])
tensor([[3, 3, 3],
        [3, 3, 3]])
tensor([[-3, -3, -3],
        [-3, -3, -3]])


tensor([[1, 2, 3],
        [3, 3, 3]])

## Reduction Operation

In [87]:
#Sum
a = torch.randint(size=(2,3),low=0, high=7, dtype=torch.float32)
print(a)
print(torch.sum(a))

#Sum along columns
print(torch.sum(a,dim=0))

#Sum along Rows
print(torch.sum(a,dim=1))


tensor([[4., 1., 4.],
        [2., 6., 0.]])
tensor(17.)
tensor([6., 7., 4.])
tensor([9., 8.])


In [92]:
#Mean
print("Mean--> ",torch.mean(a))

#Median
print("Median--> ", torch.median(a))

Mean-->  tensor(2.8333)
Median-->  tensor(2.)


In [93]:
#Max and min
print("Max--> ", torch.max(a))
print("Min--> ", torch.min(a))

Max-->  tensor(6.)
Min-->  tensor(0.)


In [95]:
#Product
print("Product--> ", torch.prod(a))

#Standard Deviation
print("Standard deviation--> ", torch.std(a))

#Variance
print("Variance--> ", torch.var(a))

Product-->  tensor(0.)
Standard deviation-->  tensor(2.2286)
Variance-->  tensor(4.9667)


In [96]:
#arg max and arg min
print("Max Item at--> ",torch.argmax(a))
print("Min Item at--> ", torch.argmin(a))

Max Item at-->  tensor(4)
Min Item at-->  tensor(5)
