In [23]:
import torch
print(torch.__version__)

2.10.0+cu128


In [24]:
if torch.cuda.is_available():
    print(f"Device: {torch.cuda.get_device_name(0)}")
else: 
    print("Device not available.")

Device: NVIDIA GeForce RTX 4060 Laptop GPU


In [25]:
# empty

a = torch.empty(2,3)
a

tensor([[-2.0340e-38,  3.0764e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [26]:
#check type
type(a)

torch.Tensor

In [27]:
#shape
print(a.shape)
#size
print(a.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [28]:
# using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [29]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [30]:
# random tensors
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [31]:
#Use of seeds
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [32]:
#Custom tensor
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [33]:
# other ways to create a tensor

#arange
print("Using arange--> ", torch.arange(0,10,2))

#using linspace
print("Using linspace--> ", torch.linspace(0,10,10))

# Using eye
print("Using Eye(Identity matrix)--> ", torch.eye(5))

# Using Full
print("Using Full--> ", torch.full((3,3), 5))

Using arange-->  tensor([0, 2, 4, 6, 8])
Using linspace-->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using Eye(Identity matrix)-->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using Full-->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [34]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [35]:
# Same shape different values
torch.empty_like(x)

tensor([[    140131522538360,      94316819050800,                   0],
        [                  0,        197568495616, 7310593858020254331]])

In [36]:
# Similarli zeroes _like and ones_like
print(torch.zeros_like(x))
print(torch.ones_like(x))

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])


## Tensor Data Types

In [37]:
x.dtype

torch.int64

In [38]:
torch.tensor([1.0,2.0,3.0], dtype=torch.float32)

tensor([1., 2., 3.])

In [39]:
# Changing data type
x.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)