In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
    print(f"Device: {torch.cuda.get_device_name(0)}")
else: 
    print("Device not available.")

Device: NVIDIA GeForce RTX 4060 Laptop GPU


In [3]:
# empty

a = torch.empty(2,3)
a

tensor([[1.0024e-34, 3.0763e-41, 0.0000e+00],
        [0.0000e+00, 3.5873e-42, 0.0000e+00]])

In [4]:
#check type
type(a)

torch.Tensor

In [5]:
#shape
print(a.shape)
#size
print(a.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [6]:
# using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# random tensors
torch.rand(2,3)

tensor([[0.3463, 0.3884, 0.8611],
        [0.2347, 0.8818, 0.4882]])

In [9]:
#Use of seeds
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
#Custom tensor
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# other ways to create a tensor

#arange
print("Using arange--> ", torch.arange(0,10,2))

#using linspace
print("Using linspace--> ", torch.linspace(0,10,10))

# Using eye
print("Using Eye(Identity matrix)--> ", torch.eye(5))

# Using Full
print("Using Full--> ", torch.full((3,3), 5))

Using arange-->  tensor([0, 2, 4, 6, 8])
Using linspace-->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using Eye(Identity matrix)-->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using Full-->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [12]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [13]:
# Same shape different values
torch.empty_like(x)

tensor([[139991655084408, 139991655084408,  94301943282032],
        [ 94301943282032,  94300301952093,  94301943281840]])

In [14]:
# Similarli zeroes _like and ones_like
print(torch.zeros_like(x))
print(torch.ones_like(x))

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])


## Tensor Data Types

In [15]:
x.dtype

torch.int64

In [16]:
torch.tensor([1.0,2.0,3.0], dtype=torch.float32)

tensor([1., 2., 3.])

In [17]:
# Changing data type
x.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## Maths Operations

In [18]:
#Scalar operations

#Add
x + 2

#Subtract
x -2

#Multiply
x*3

#Divide
x/2

#Power
x**2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

## Element wise Operations

In [19]:
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[n for n in range(4,7)],[n for n in range(1,4)]])

#ADD
print(x+y)

#SUB
print(x-y)

#MUL
print(x*y)

#DIV
print(x/y)

#POWER
print(x**y)

#abs
print(abs(x-y))

#negative
print(torch.neg(abs(x-y)))

#round, floor, ceil

#clamp
torch.clamp(x,min=1,max=3)


tensor([[5, 7, 9],
        [5, 7, 9]])
tensor([[-3, -3, -3],
        [ 3,  3,  3]])
tensor([[ 4, 10, 18],
        [ 4, 10, 18]])
tensor([[0.2500, 0.4000, 0.5000],
        [4.0000, 2.5000, 2.0000]])
tensor([[  1,  32, 729],
        [  4,  25, 216]])
tensor([[3, 3, 3],
        [3, 3, 3]])
tensor([[-3, -3, -3],
        [-3, -3, -3]])


tensor([[1, 2, 3],
        [3, 3, 3]])

## Reduction Operation

In [20]:
#Sum
a = torch.randint(size=(2,3),low=0, high=7, dtype=torch.float32)
print(a)
print(torch.sum(a))

#Sum along columns
print(torch.sum(a,dim=0))

#Sum along Rows
print(torch.sum(a,dim=1))


tensor([[1., 1., 6.],
        [3., 4., 5.]])
tensor(20.)
tensor([ 4.,  5., 11.])
tensor([ 8., 12.])


In [21]:
#Mean
print("Mean--> ",torch.mean(a))

#Median
print("Median--> ", torch.median(a))

Mean-->  tensor(3.3333)
Median-->  tensor(3.)


In [22]:
#Max and min
print("Max--> ", torch.max(a))
print("Min--> ", torch.min(a))

Max-->  tensor(6.)
Min-->  tensor(1.)


In [23]:
#Product
print("Product--> ", torch.prod(a))

#Standard Deviation
print("Standard deviation--> ", torch.std(a))

#Variance
print("Variance--> ", torch.var(a))

Product-->  tensor(360.)
Standard deviation-->  tensor(2.0656)
Variance-->  tensor(4.2667)


In [24]:
#arg max and arg min
print("Max Item at--> ",torch.argmax(a))
print("Min Item at--> ", torch.argmin(a))

Max Item at-->  tensor(2)
Min Item at-->  tensor(0)


## Matrix Operations

In [25]:
f = torch.randint(size=(3,3), low = 1, high = 10, dtype=torch.float32)
g = torch.randint(size=(3,3), low = 1, high = 10, dtype=torch.float32)

print(f)
print(g)

tensor([[9., 6., 1.],
        [2., 6., 1.],
        [4., 9., 2.]])
tensor([[6., 7., 1.],
        [2., 4., 7.],
        [4., 7., 8.]])


In [26]:
#Matrix Multiplication
torch.matmul(f,g)

tensor([[70., 94., 59.],
        [28., 45., 52.],
        [50., 78., 83.]])

In [27]:
#Dot product
vector1 = torch.randint(size=(5,),low=1, high=10)
vector2 = torch.randint(size=(5,),low=1, high=10)
torch.dot(vector1, vector2)

tensor(216)

In [28]:
#Transpose
torch.transpose(f, 0, 1)

tensor([[9., 2., 4.],
        [6., 6., 9.],
        [1., 1., 2.]])

In [29]:
#Determinant
torch.det(f)

tensor(21.0000)

In [30]:
torch.inverse(f)

tensor([[ 1.4286e-01, -1.4286e-01,  2.1524e-08],
        [ 2.6609e-09,  6.6667e-01, -3.3333e-01],
        [-2.8571e-01, -2.7143e+00,  2.0000e+00]])

## Copying a Tensor

In [31]:
a = torch.randint(size=(2,3), low=1, high=10)
a

tensor([[7, 6, 7],
        [4, 1, 7]])

In [32]:
b = torch.clone(a)
b

tensor([[7, 6, 7],
        [4, 1, 7]])

In [33]:
print("ID of a--> ", id(a))
print("ID of b--> ", id(b))

ID of a-->  139985271592912
ID of b-->  139985271587408


## Tensor Operations on a GPU

In [34]:
torch.cuda.is_available()

True

In [35]:
device = torch.device('cuda')

In [36]:
#Making a new tensor on our GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [37]:
#Moving to a GPU
a = torch.rand(2,3)
print(a)
b = a.to(device)
print(b)

tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])
tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]], device='cuda:0')


In [38]:
# Comparision between GPU and CPU
import time

a = torch.rand(10000,10000)
b = torch.rand(10000,10000)

start_time_cpu = time.time()
result_cpu = torch.matmul(a,b)
end_time_cpu = time.time()
print("CPU Time--> ", end_time_cpu-start_time_cpu)

c = a.to(device)
d = b.to(device)

start_time_gpu = time.time()
result_gpu = torch.matmul(c,d)
end_time_gpu = time.time()
print("CPU Time--> ", end_time_gpu-start_time_gpu)

CPU Time-->  5.201561212539673
CPU Time-->  0.17271089553833008


## Reshaping Tensors

In [39]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [41]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
b = torch.rand(2,3,4)
b

tensor([[[0.2774, 0.8399, 0.9186, 0.5959],
         [0.5539, 0.3423, 0.1570, 0.2660],
         [0.3715, 0.6096, 0.5115, 0.0678]],

        [[0.5038, 0.7779, 0.2659, 0.3932],
         [0.7483, 0.7985, 0.4626, 0.9414],
         [0.5752, 0.8881, 0.7989, 0.9514]]])

In [47]:
#permute
print(b.permute(2,0,1))
print(b.permute(2,0,1).shape)

tensor([[[0.2774, 0.5539, 0.3715],
         [0.5038, 0.7483, 0.5752]],

        [[0.8399, 0.3423, 0.6096],
         [0.7779, 0.7985, 0.8881]],

        [[0.9186, 0.1570, 0.5115],
         [0.2659, 0.4626, 0.7989]],

        [[0.5959, 0.2660, 0.0678],
         [0.3932, 0.9414, 0.9514]]])
torch.Size([4, 2, 3])


In [48]:
#unsqeeze
#image size
c = torch.rand(226,226,3)
print(c.unsqueeze(0))
print(c.unsqueeze(0).shape)

tensor([[[[0.0141, 0.8903, 0.1649],
          [0.3162, 0.1331, 0.6763],
          [0.4254, 0.2375, 0.5430],
          ...,
          [0.0458, 0.0810, 0.8235],
          [0.0526, 0.8029, 0.1183],
          [0.8943, 0.6250, 0.2099]],

         [[0.8299, 0.9260, 0.8240],
          [0.0352, 0.8451, 0.5813],
          [0.0769, 0.8940, 0.4108],
          ...,
          [0.1390, 0.1333, 0.0787],
          [0.4590, 0.8408, 0.3800],
          [0.8294, 0.9181, 0.0590]],

         [[0.0191, 0.7097, 0.5266],
          [0.9376, 0.5448, 0.9703],
          [0.8731, 0.0289, 0.1019],
          ...,
          [0.9432, 0.3207, 0.8048],
          [0.7517, 0.4902, 0.3576],
          [0.5585, 0.7695, 0.7475]],

         ...,

         [[0.3756, 0.0879, 0.1557],
          [0.4039, 0.3626, 0.3724],
          [0.2468, 0.8261, 0.8907],
          ...,
          [0.3614, 0.7389, 0.8816],
          [0.2554, 0.7735, 0.4978],
          [0.1188, 0.4220, 0.4836]],

         [[0.5745, 0.5065, 0.8767],
          [0.3764

In [50]:
#Squeeze
d = torch.rand(1,20)
print(d.squeeze(0))
print(d.squeeze(0).shape)

tensor([0.9453, 0.2751, 0.9386, 0.9695, 0.5577, 0.7613, 0.9780, 0.4076, 0.0069,
        0.3317, 0.4557, 0.6627, 0.3284, 0.6639, 0.4576, 0.9338, 0.5387, 0.2537,
        0.9280, 0.7146])
torch.Size([20])
